config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get 'about', to: 'static_pages#about', as: 'about'

  get   'boards',         to: 'boards#index', as: 'boards'
  get   'boards/new',     to: 'boards#new',   as: 'new_board'
  post  'boards',         to: 'boards#create'
  get   'board/:id',      to: 'boards#show',  as: 'board'
  get   'board/:id/edit', to: 'boards#edit'
  patch 'board/:id',      to: 'boards#update'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController

  # GET /boards
  def index
    @boards = Board.all
  end

  # GET /boards/1
  def show
    @board = Board.find(params[:id])
  end

  # GET /boards/new
  def new
    @board = Board.new
  end

  # GET /boards/1/edit
  def edit
    @board = Board.find(params[:id])
  end

  # POST /boards
  def create
    @board = Board.new(board_params)

    respond_to do |format|
      if @board.save
        redirect_to @board, notice: 'Board was successfully created.'
      else
        render :new
      end
    end
  end

  # PATCH/PUT /boards/1
  def update
    @board = Board.find(params[:id])
    respond_to do |format|
      if @board.update(board_params)
        redirect_to @board, notice: 'Board was successfully updated.'
      else
        render :edit 
      end
    end
  end

  private
  # Never trust parameters from the scary internet, only allow the white list through.
  def board_params
    params.fetch(:board, {})
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    render html: "hello, world!"
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/boards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Boards</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @boards.each do |board| %>
      <tr>
        <td><%= link_to 'Show', board %></td>
        <td><%= link_to 'Edit', edit_board_path(board) %></td>
        <td><%= link_to 'Destroy', board, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Board', new_board_path %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-dark bg-inverse">
  <%= link_to "Movie Reviews", root_path, class: "navbar-brand" %>
  <ul class="nav navbar-nav">

    <li class="nav-item active">
      <a class="nav-link" href="movies/new">New Movie <span class="sr-only">(current)</span></a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#">About</a>
    </li>
  </ul>
  <form class="form-inline pull-xs-right">
    <input class="form-control" type="text" placeholder="Search">
    <button class="btn btn-success-outline" type="submit">Search</button>
  </form>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ranban</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/home.html.erb
<h1>StaticPages#home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>